### ISSUE TITLE
errors compiling with dmd 2.061 (beta)

### ISSUE THREAD

**Issue by jordisayol** [mdparker/Derelict3#79]
I got this error compiling to 32-bit with the last dmd 2.061 beta on Linux:

```
derelict/lua/types.d(58): Error: struct derelict.lua.types.lua_State unknown size
derelict/lua/types.d(58): Error: struct derelict.lua.types.lua_State no size yet for forward reference
```

No problem when compiling to 64-bit.

**Comment by mdparker** [comment]
Well, I have no way right now to try this out on Linux. But it builds fine on Windows with 2.061. Are you using build.d to compile? If not, try that and see how it goes.

**Comment by jordisayol** [comment]
Yes, I'm using build.d to compile it.

**Comment by mdparker** [comment]
OK, then it sounds like you've stumbled upon a regression. What you should do next is come up with a minimal test case to report to the DMD bugzilla. The offending line is this:

struct lua_State;

This is valid D. And the same idiom is used throughout Derelict in other bindings. So see if you can compile the following by itself:

struct Foo;
Foo\* function() GetFoo;

**Comment by jordisayol** [comment]
This code do not return any error in both 32-bit and 64-bit:

```
struct Foo;
void main()
{
    Foo* function() GetFoo;
}
```

**Comment by mdparker** [comment]
Alright. I have Linux Mint installed on my old box. I can probably find some time in the next few days to get it set up and see if I can reproduce it there. But in the meantime, if you could try to reduce it, perhaps using Dustmite, you could probably get it done sooner.

**Comment by mdparker** [comment]
Just a progress report. My old box is 32-bit, so just to make sure I've got a similar environment, I've installed 64-bit Linux Mint on a new partition on my current box. In another day or two, I'll get around to installing 2.061 beta and trying to reproduce this.

**Comment by jordisayol** [comment]
Why you don't use VirtualBox for testing?
BTW the problem is only present on Linux 32-bit.

**Comment by mdparker** [comment]
I understood that you were compiling on a 64-bit system with -m32. Are you compiling on a 32-bit system?

I've never had a good experience with virtual box. It's been a while since I've used it, though. At any rate, it would really help me out if you could try to narrow it down yourself.

**Comment by jordisayol** [comment]
Yes, I compiled it in a 64-bit system with -m32. So now I've tested on a LinuxMint 14 32-bit with the same result.
 when compiling to 32-bit:

```
../derelict/lua/types.d(58): Error: struct derelict.lua.types.lua_State unknown size
../derelict/lua/types.d(58): Error: struct derelict.lua.types.lua_State no size yet for forward reference
```

No problem when compiling to 64-bit on this 32-bit system.

BTW, Happy new year! :-)

**Comment by mdparker** [comment]
Alright, I finally got the environment configured and found the problem. This is actually a "progression" of sorts, rather than a regression. The problem was that lua_newstate was declared to return a lua_State by value, when lua_State is defined as an opaque struct. It should have been returning a lua_State*. So, the error message was pointing to the wrong location, but that was the problem. I can't believe it's been compiling at all until now. That should always be an error I think. Thanks for reporting. And Happy New Year!

**Comment by jordisayol** [comment]
Solved! Thank You!
